export const englishFrequencies = [
  { letter: "E", freq: 12.7 },
  { letter: "T", freq: 9.1 },
  { letter: "A", freq: 8.2 },
  { letter: "O", freq: 7.5 },
  { letter: "I", freq: 7.0 },
  { letter: "N", freq: 6.7 },
  { letter: "S", freq: 6.3 },
  { letter: "H", freq: 6.1 },
  { letter: "R", freq: 6.0 },
  { letter: "D", freq: 4.3 },
  { letter: "L", freq: 4.0 },
  { letter: "C", freq: 2.8 },
  { letter: "U", freq: 2.8 },
  { letter: "M", freq: 2.4 },
  { letter: "W", freq: 2.4 },
  { letter: "F", freq: 2.2 },
  { letter: "G", freq: 2.0 },
  { letter: "Y", freq: 2.0 },
  { letter: "P", freq: 1.9 },
  { letter: "B", freq: 1.5 },
  { letter: "V", freq: 1.0 },
  { letter: "K", freq: 0.8 },
  { letter: "J", freq: 0.15 },
  { letter: "X", freq: 0.15 },
  { letter: "Q", freq: 0.1 },
  { letter: "Z", freq: 0.07 },
];
